name: SnapGarden_CPU
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.15

  # Required for compatibility
  - pip

  # Pip-only packages
  - pip:
      - packaging==23.2
      - addict==2.4.0
      - editdistance==0.6.2
      - einops==0.7.0
      - fairscale==0.4.0
      - jsonlines==4.0.0
      - markdown2==2.4.10
      - matplotlib==3.7.4
      - numpy==1.24.4
      - opencv_python_headless==4.5.5.64
      - openpyxl==3.1.2
      - Pillow==10.1.0
      - torch==2.1.2
      - torchvision==0.16.2
      - transformers==4.40.0
      - uvicorn==0.24.0.post1
      - accelerate==0.30.1
      - argon2-cffi
      - peft
      - fastapi[all]