name: SnapGarden_CPU
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11.11
  
  # Core ML Libraries (conda-installed)
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.1
  - scikit-learn=1.6.1
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - tqdm=4.67.1
  - numba=0.60.0
  - jupyterlab
  - nb_conda_kernels

  # Required for compatibility
  - pip
  - setuptools=68.2.2

  # Pip-only packages
  - pip:
    # TensorFlow
    - tensorflow==2.17.1
    
    # Hugging Face Ecosystem
    - transformers==4.47.1
    - datasets==3.2.0
    - accelerate==1.2.1
    - safetensors==0.5.2
    - sentencepiece==0.2.0
    
    # JAX (CPU version)
    - jax==0.4.33
    - jaxlib==0.4.33
    
    # Vision
    - opencv-python==4.10.0.84
    - pillow==11.1.0
    
    # Visualization
    - plotly==5.24.1
    
    # Gradient Boosting
    - xgboost==2.1.3
    - lightgbm==4.5.0
    
    # Quantization (CPU-compatible)
    - bitsandbytes==0.45.1