name: SnapGarden_CPU
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # Core packages via conda
  - pytorch=2.0.1=cpu_py310h*  # Explicit CPU build
  - torchvision=0.15.2=cpu_py310h*
  # ML ecosystem
  - transformers=4.34.0
  - peft=0.6.2
  - datasets=2.14.5
  # Web server
  - fastapi=0.103.2
  - uvicorn=0.23.2
  # System utilities
  - pip=23.3.1
  - numpy=1.24.3
  # Pure Python packages via pip
  - pip:
      - torchaudio==2.0.2+cpu
      - accelerate==0.24.1  # Required for PEFT
      - bitsandbytes==0.41.3.1  # CPU-compatible version